### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by jussipvainionpaa** [F1DNA/FlexFarmerAsAService#1]
I did everything exactly like in the README but when I check the status of the service I get:

flexfarmer.service - https://github.com/F1DNA/FlexFarmerAsAService
     Loaded: loaded (/etc/systemd/system/flexfarmer.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-09-17 15:26:01 EEST; 916ms ago
    Process: 101925 ExecStart=/usr/local/bin/flexfarmer -c /home/flexfarmer/.config/flexfarmer/config.yml (code=exited, status=1/FAILURE)
   Main PID: 101925 (code=exited, status=1/FAILURE)

syys 17 15:26:01 plotter systemd[1]: flexfarmer.service: Scheduled restart job, restart counter is at 5.
syys 17 15:26:01 plotter systemd[1]: Stopped https://github.com/F1DNA/FlexFarmerAsAService.
syys 17 15:26:01 plotter systemd[1]: flexfarmer.service: Start request repeated too quickly.
syys 17 15:26:01 plotter systemd[1]: flexfarmer.service: Failed with result 'exit-code'.
syys 17 15:26:01 plotter systemd[1]: Failed to start https://github.com/F1DNA/FlexFarmerAsAService.

**Comment by jussipvainionpaa** [comment]
Seems that just rebooting the machine fixed it.

I would add a reboot to the README after the "Restart syslog" and "Restart systemctl daemon"

**Comment by F1DNA** [comment]
Thanks for following up.  Not sure what caused you to need to reboot.  I ran through this several times without needing to and have not heard this from anyone else.  If it becomes a pattern, I will revisit this.  For now, leaving it as is.
